# Generated by Django 4.0.4 on 2022-04-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountIncomingMailStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.TextField(default="")),
                ("message_id", models.TextField(default="")),
                ("sent_date_time", models.DateTimeField(default=None, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_read_date_time", models.DateTimeField(default=None, null=True)),
                ("read_time_taken", models.FloatField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(default="", max_length=255)),
                ("is_connected", models.BooleanField(default=False)),
                ("access_token", models.TextField(default="")),
                ("refresh_token", models.TextField(default=None, null=True)),
                (
                    "access_token_expire_date",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "refresh_token_expire_date",
                    models.DateTimeField(default=None, null=True),
                ),
                ("is_sync_running", models.BooleanField(default=False)),
                ("is_sync_completed", models.BooleanField(default=False)),
                ("last_job_run", models.DateTimeField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegratedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connected_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.connectedaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountOutgoingMailStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.TextField(default="")),
                ("message_id", models.TextField(default="")),
                ("sent_date_time", models.DateTimeField(default=None, null=True)),
                ("response_time", models.IntegerField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.connectedaccount",
                    ),
                ),
                (
                    "inbox_email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.accountincomingmailstats",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accountincomingmailstats",
            name="connected_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.connectedaccount",
            ),
        ),
    ]
