# Generated by Django 4.0.4 on 2022-04-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectedaccount",
            name="is_connected",
        ),
    ]
